eureka:
  client:
    serviceUrl:
      #local
      defaultZone: http://localhost:8761/eureka/
      #docker
      #defaultZone: http://microservicio-eureka:8761/eureka/
  instance:
    preferIpAddress: true

springdoc:
  api-docs:
    path: /usuario/v1/api-docs
  swagger-ui:
    path: /usuario/swagger-ui.html

openapi:
  service:
    title: usuario
    version: 1.0.0